@echo off
REM Gradle wrapper script for Windows
REM Generated by assistant for Gradle 8.5
setlocal
if "%JAVA_HOME%"=="" (
  set "JAVACMD=java"
) else (
  set "JAVACMD=%JAVA_HOME%\bin\java"
)
if not defined JAVACMD (
  echo ERROR: Java not found. Please set JAVA_HOME or install Java.
  exit /b 1
)
set PRG=%~dp0\gradle\wrapper\gradle-wrapper.jar
"%JAVACMD%" -cp "%PRG%" org.gradle.wrapper.GradleWrapperMain %*
